version: '3.7'
services:
  backend:
    build: .
    container_name: backend
    restart: always
    expose:
      - 5000
    env_file:
      - .env
    networks:
      - web
networks:
    web:
      name: web
      external: true
